### ISSUE TITLE
Plugin Back up and Features

### ISSUE THREAD

**Issue by ghost** [ltguide/CraftBukkit-MineBackup#2]
I see that your quite active on your plugin so maybe you a few new features to it?

For me the plugin backup isn't working the setting is true but it isn't backing them up. Is this normal?

Also can you a setting to limit the amount of backups?

For example when I make a backup every 10 minutes and i would set the keep days to 2 I would have a ton of backups.

But adding a amount limit like 25 will limit how much backups there can be in total. Keeping a more strict limit on the size.

Or even better add a size limit too for example 1024 MB.

Also maybe a setting when no one is in the server the timer will reset and when someone join it starts the delay, then the backup and then follows the main interval time.

Thanks great plugin :D

**Comment by ltguide** [comment]
I have this set and it's zipping the plugins up once an hour. Since compress is true, it's pulling in the 1h interval from default_settings. Check what it says for plugins in the output of `/minebackup status`.

```
<snip>
default_settings:
  compress: 1h
<snip>
others:
  plugins:
    copy: false
    compress: true
    dropbox: false
    exclude-folders:
    - tiles
    exclude-types:
    - jar
```

The `keep` setting is the number of backups to keep on disk. It maxes at 24 atm so with a copy/compress of 10 minutes, you would have 4 hours to go back.

I'm hesitant to add a size check on the folder because of the needed I/O operations.

It already automatically pauses when there are no players.

Anything else, let me know :)
